import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import {ICountry} from '../interfaces';
import FrontEndController from '../frontEndController'


interface IColumn {
  key: string;
  name: string;
  fieldName: string;
  minWidth: number;
  maxWidth: number;
  isResizable: boolean;
}

export interface IProps {
  countries: ICountry[];
}

const columns = [
  { key: 'name', name: 'Name des Landes', fieldName: 'name', minWidth: 100, maxWidth: 200, isResizable: true },
  { key: 'area', name: 'Fläche', fieldName: 'area', minWidth: 100, maxWidth: 200, isResizable: true },
  { key: 'population', name: 'Einwohnerzahl', fieldName: 'population', minWidth: 100, maxWidth: 200, isResizable: true },
  { key: 'leader', name: 'Staatsoberhaupt', fieldName: 'leader', minWidth: 100, maxWidth: 200, isResizable: true },
  { key: 'phone', name: 'Telefonvorwahl', fieldName: 'phone', minWidth: 100, maxWidth: 200, isResizable: true },
]

const Home: NextPage = ({countries}: InferGetStaticPropsType<typeof getStaticProps>) => {
  // create state for countries
  const [countriesState, setCountries] = useState<ICountry[]>(countries);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          <u>Länder der Welt</u>
        </h1>
        <table>
          <thead>
            <tr>
              {columns.map((column) => (
                <th key={column.key}>{column.name}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {countriesState.map((country, index) => (
              <tr key={index}>
                {columns.map((column) => (
                  <td key={column.key}>{country[column.fieldName as keyof typeof country]}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const countries = await FrontEndController.getAllCountries();
  return {
    props: {
      countries: countries,
    },
  };
}

export default Home